[package]
name = "tcss360-project"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.16.1", features = ["glam_assert", "file_watcher"] }
bevy_ecs_tilemap = { version = "0.16.0", features = ["atlas"] }
bevy_pixcam = "0.16.0"
rand = { version = "0.9.1", features = ["log"] }

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
